obj-$(CONFIG_COLTRANE_MCU) += mcu-spi.o

obj-$(CONFIG_COLTRANE_MCU) += mcu-bootloader.o

obj-$(CONFIG_COLTRANE_MCU) += mcu-app.o
mcu-app-y += mcu-app-core.o
mcu-app-y += mcu-descriptor.o
mcu-app-y += mcu-app-mmap.o
mcu-app-y += mcu-app-io.o
mcu-app-y += capnp/capn.o
mcu-app-y += capnp/capn-malloc.o
mcu-app-y += capnp/capn-stream.o
mcu-app-y += capnp/mcu-descriptor-capnp.o
